name: Auto Assign Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue based on label
        uses: pozil/auto-assign-issue@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label: "good first issue"
          assignees: "contributor1, contributor2"
